# Generated by Django 5.1.7 on 2025-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-date", "title"]},
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="published_date",
            new_name="date",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Amit Bhalla", max_length=100),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="read_time",
            field=models.PositiveIntegerField(
                default=5, help_text="Estimated reading time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=200
            ),
        ),
    ]
